### ISSUE TITLE
Dark Skin

### ISSUE THREAD

**Issue by Cdddo** [gwaredd/UnityMarkdownViewer#4]
Would be really nice to have a dark skin!

**Comment by gwaredd** [comment]
You can change the skin by editing Editor/Skin ...

**Comment by MostHated** [comment]
It would be super helpful if there was a dark skin included that could be selected, or detect the current Editor skin and apply it.

**Comment by gwaredd** [comment]
It should be relatively easy, do you have a theme already?

**Comment by MostHated** [comment]
I do not. I tried to see if I could edit the one that was included, but for some reason, as soon as I click on the skin file my editor seems to come to nearly a complete halt and trying to click on anything within the skin file takes nearly 30 seconds to get a result. As soon as I click off/away from the skin file so that it is deselected, everything is fine again. Trying to simply locate and edit  wherever I would need to, to simply change the background color became quite frustrating rather quickly.

It was a rather small project with no much going on to begin with, and I know it is not my pc as I have a R9 3950x with 64gb ram. I have not really dealt with skin files much in the past, though, so I am not sure if this is a common occurrence? 

I don't know if they are setup specifically per application/useage to where I could try and locate one from some other project and use it, but considering now that the Unity editor comes with a dark theme enabled by default, (the super bright white backgound really hits you in the eyes if you are not expecting it, lol) it would be great if one were included and enabled by default.

**Comment by gwaredd** [comment]
I'll have to "roadmap" this feature until I have a bit more time ...

**Comment by MostHated** [comment]
Hey there,
   I just saw the update with the dark skin, looks so much nicer, so thanks for that. One thing I noticed as soon as I opened it up though and clicked on the README.md was this:

![](https://i.imgur.com/PA3MR25.png)

The text seems to be overlapping the above header? I will try it out in a fresh project though to make sure it's not something on my end.


---- 
Edit

 Looks like it might be on my end, I tried it on a fresh 2020.1 project, the prior was 2019.4.x, and it seems like the overlap is good in this one, but the actual size of the view area is restricted.

![](https://i.imgur.com/8KjkYvn.png)

**Comment by gwaredd** [comment]
Checked in an update, see if that helps

**Comment by MostHated** [comment]
Hmmm.. I did a pull and saw the changes, deleted it from both the 2019.4 and 2020.1 projects and copied it in fresh, but had the same result in both. Just to be sure, I deleted it entirely, recloned it, tried again, still the same for some reason, where the view is only about 1/3 of the overall inspector panel. It looks great otherwise, at least. 👍 lol

![](https://i.imgur.com/3wxhpVw.png)

**Comment by Theadd** [comment]
https://github.com/gwaredd/UnityMarkdownViewer/issues/4#issuecomment-731654067
> the view is only about 1/3 of the overall inspector panel.

https://github.com/gwaredd/UnityMarkdownViewer/blob/295c6b8b933f3ff68855d8e079a6118a31c88c2c/Editor/Scripts/MarkdownViewer.cs#L85-L87

It's more of a patch than a fix but changing the lines above to the following ones provides a better view
```csharp
            // fix for Screen.height
            var offset = 0.0f;
            var scale  = 1.6f;
```

**Comment by MostHated** [comment]
Ok, nice. I was able to get it looking solid with the following by changing offset to be an additional amount instead of subtracting:

```cs
// fix for Screen.height
var offset = 300.0f;
var scale  = 1.6f;

// calculate working space
if( Event.current.type == EventType.Layout )
{
    mHeight = ( Screen.height + offset ) / scale;
}
```
Not sure if that might end up causing other issues elsewhere, but at least with just checking around a little, it seems to be solid like that.

![](https://i.imgur.com/IH5zGi5.png)

**Comment by gwaredd** [comment]
I see the issue here. As far as I can tell, the `MarkdownViewer.Draw()` code is a pile of nonsense! ;)
